platform :ios, '9.0'

target 'FIUBA' do
  use_frameworks!

  # Pods for FIUBA
  pod 'RealmSwift'

  target 'FIUBATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FIUBAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
